# Generated by Django 2.1 on 2019-09-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190904_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, height_field=100, upload_to='company', width_field=100),
        ),
    ]
